/** Copy for the HUD frame. Word for word from the writer notes. */
export const TITLE_OWNER = "Your apartment";
export const TITLE_WATCH = "The apartment";
export const BADGE_WATCH = "WATCHING · READ-ONLY";
export const HERE = "Here";
export const HERE_EMPTY = "No one's home right now.";
export const RADIO_OFF = "The radio is off.";
export const PLAY = "Play";
export const STOP = "Stop";
export const MUTE = "Mute";
export const UNMUTE = "Unmute";
export const PREVIOUS = "Previous station";
export const NEXT = "Next station";
export const PLAYING = "Playing";
export const PLAYS = (station: string) => `Plays ${station}`;
export const STREAM_FAIL = "Can't play this station right now.";
export const ACTION_FAIL = "That didn't go through. Try again.";
export const TV_OFF_WATCH = "The TV is off.";
export const TV_OFF = "Off";
export const TURN_ON = "Turn on";
export const TURN_OFF = "Turn off";
export const LOOK_OUTSIDE = "Look outside";
export const TODAY_EMPTY = "Nothing new today.";
export const SUNSET = (time: string) => `Sunset at ${time}.`;
export const SUNRISE = (time: string) => `Sunrise at ${time}.`;
export const OPENS_NEW_TAB = "(opens in a new tab)";
export const ACTIVITY = "Activity";
export const SHOW_CONTROLS = "Show controls";
export const CLOSE = "Close";
export const ROOM_SOUND = "Room sound";
export const WATCH_YOU = "You're watching. Only the owner can change things here.";
export const OWNER_ONLY = "Only the owner can change things here.";
export const COMING_SOON = "Coming soon.";
export const HOUSE = "House";
export const DAY = "Day";
export const DUSK = "Dusk";
export const NIGHT = "Night";
export const NOTHING = "Nothing new today.";
export const OFFLINE = "Can't connect. Check your connection.";
